version: '3'

services:
  api_sfl:
    container_name: api_sfl
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8040:8040"
      - "9040:9001"
    volumes:
      - .:/app
    command: symfony serve --dir=app/public --port=8040 --force-php-discovery
